<?php


use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class Firms extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $firms = [
            'Intel',
            'AMD',
            'NVIDIA',
            'AMD',
            'HyperX',
            'Logitech',
            'Razer',
            'A4Tech',
            'HP Omen',
            'ASUS',
            'MSI',
            'Acer',
            'Steelseries',
            'Corsair',
            'Redragon',
            'Dell',
            'Zowie',
            'Lenovo',
            'Red Square',
            'Sven',
            'Defender',
            'Dark Project',
            'Cooler Master',
            'Thermaltake',
            'Cougar',
            'Alienware',
            'DEXP',
            'Oklick',
            'Thunder x3',
            'GAMDIAS',
            'Qcyber',
            'Hermes',
            'Trust GXT',
            'ZET Gaming',
            'Aorus',
            'GIGABYTE',
            'HyperX',
            'Logitech',
            'Razer',
            'A4Tech',
            'HP Omen',
            'ASUS',
            'MSI',
            'Acer',
            'Steelseries',
            'Corsair',
            'Redragon',
            'Dell',
            'Zowie',
            'Lenovo',
            'Red Square',
            'Sven',
            'Defender',
            'Dark Project',
            'Cooler Master',
            'Thermaltake',
            'Cougar',
            'Alienware',
            'DEXP',
            'Oklick',
            'Thunder x3',
            'GAMDIAS',
            'Qcyber',
            'Hermes',
            'Trust GXT',
            'ZET Gaming',
            'Aorus',
            'GIGABYTE',
            'HyperX',
            'Logitech',
            'Razer',
            'A4Tech',
            'HP',
            'ASUS',
            'MSI',
            'Acer',
            'Steelseries',
            'Corsair',
            'Redragon',
            'Dell',
            'Zowie',
            'Lenovo',
            'Red Square',
            'Sven',
            'Defender',
            'Dark Project',
            'Cooler Master',
            'Cougar',
            'Thermaltake',
            'JBL',
            'Plantronics',
            'Sennheiser',
            'HP Omen',
            'Alienware',
            'Oklick',
            'Thunder x3',
            'GAMDIAS',
            'Qcyber',
            'Hermes',
            'DEXP',
            'Trust GXT',
            'ZET Gaming',
            'Aorus',
            'GIGABYTE',
            'Acer',
            'ASUS',
            'AeroCool',
            'COUGAR',
            'Cooler Master',
            'Corsair',
            'Sharkoon',
            'DxRacer',
            'GIGABYTE',
            'MSI',
            'WARP',
            'Red Square',
            'Redragon',
            'ThunderX3',
            'Thermaltake',
            'Vertagear',
            'Tesoro',
            'Akracing',
            'VMM Gaming',
            'X-cyber',
            'Chairman',
            'Viking',
            'Trust GXT',
            'ZET Gaming',
            'Aorus',
            'Acer',
            'AOC',
            'ASUS',
            'BenQ',
            'Cooler Master',
            'DELL',
            'Alienware',
            'HP Omen',
            'MSI',
            'LG',
            'Samsung',
            'Liyama',
            'Zowie',
            'ZET Gaming',
            'Aorus',
            'GIGABYTE',
        ];


        $firms = array_unique($firms);
        $dataSave = [];

        foreach ($firms as $id => $firm){
            $dataSave[] = [
                'title' => $firm,
                'slug' => str_slug($firm)

            ];
        }

        \DB::table('firms')->insert($dataSave);
    }
}
